// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/public/auth": {
            "get": {
                "description": "Страница авторизации",
                "produces": [
                    "text/html"
                ],
                "summary": "Authorization",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/public/auth/post": {
            "post": {
                "description": "Отправка данных пользователя в базу данных на странице авторизации",
                "summary": "Authorization posting data",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/public/reg": {
            "get": {
                "description": "Страница регистрации",
                "produces": [
                    "text/html"
                ],
                "summary": "Registration",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/public/reg/post": {
            "post": {
                "description": "Отправка данных пользователя в базу данных на странице регистрации",
                "summary": "Registration posting data",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/:id/about": {
            "get": {
                "description": "Основная информация о проекте",
                "produces": [
                    "text/html"
                ],
                "summary": "About",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/:id/notes": {
            "get": {
                "description": "Заметки пользователя",
                "summary": "User's notes here",
                "responses": {}
            }
        },
        "/users/:id/notes/delete": {
            "post": {
                "description": "Удаление заметок пользователя",
                "summary": "Deleting user's notes here",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
