info:
  contact: {}
paths:
  /public/auth:
    get:
      description: Страница авторизации
      produces:
      - text/html
      responses:
        "200":
          description: OK
      summary: Authorization
  /public/auth/post:
    post:
      description: Отправка данных пользователя в базу данных на странице авторизации
      responses:
        "200":
          description: OK
      summary: Authorization posting data
  /public/reg:
    get:
      description: Страница регистрации
      produces:
      - text/html
      responses:
        "200":
          description: OK
      summary: Registration
  /public/reg/post:
    post:
      description: Отправка данных пользователя в базу данных на странице регистрации
      responses:
        "200":
          description: OK
      summary: Registration posting data
  /users/:id/about:
    get:
      description: Основная информация о проекте
      produces:
      - text/html
      responses:
        "200":
          description: OK
      summary: About
  /users/:id/info:
    get:
      description: Основная информация о проекте
      produces:
      - text/html
      responses:
        "200":
          description: OK
      summary: Info
  /users/:id/notes:
    get:
      description: Заметки пользователя
      produces:
      - text/html
      responses:
        "200":
          description: OK
      summary: User's notes here
  /users/:id/notes/delete:
    post:
      description: Удаление заметок пользователя
      responses: {}
      summary: Deleting user's notes here
swagger: "2.0"
